package com.goflash.dispatch.type

 enum class TaskStatus {
    CREATED, AT_LOCATION, COMPLETED, CANCELLED, UNFINISHED, POSTPONED, PAYMENT_COMPLETED, PAYMENT_INITIATED, CANCELLED_BY_CUSTOMER, TRIP_UPDATED,SHIPMENT_ADDED,SHIPMENT_REMOVED,
     TRIP_ASSIGNED,TRIP_REMOVED,ALL_SHIPMENT_REMOVED,BLOCKED,PRIORITY_UPDATED,QR_SUCCESS,QR_FAILED;
}
